# Generated by Django 5.1.7 on 2025-03-12 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0010_voto_dni_votante_alter_voto_votante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voto',
            name='dni_votante',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
