# Generated by Django 5.0.13 on 2025-03-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votaciones', '0011_alter_voto_dni_votante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='votante',
        ),
        migrations.DeleteModel(
            name='Candidato',
        ),
        migrations.DeleteModel(
            name='Votante',
        ),
        migrations.DeleteModel(
            name='Voto',
        ),
    ]
